### ISSUE TITLE
Add Continuous integration/Continuous deployment

### ISSUE THREAD

**Issue by charlenehunter** [CodingBlackFemales/cbf-community-website#23]
Currently we are using Firebase and GitHub

Add in a link to create automatic deployment when a Pull Request is approved

**Comment by yanco9a** [comment]
@charlenehunter Update: It was a toss up between CircleCi and Travis🥇 in the end. But based on languages supported i think Travis should fit CI requirements. You should receive a permissions request from Travis soon. As mentioned before this should suffice for Open source projects

**Comment by charlenehunter** [comment]
That sounds great! I’m not by my computer right now, but I’ll authorise in a couple hours and take a look. 

Charlene 

codingblackfemales.com
@codingblackfemales
Twitter: @codingblackfems

**Comment by yanco9a** [comment]
Brilliant thanks.

**Comment by charlenehunter** [comment]
It’s been authorised! 

Charlene 

codingblackfemales.com
@codingblackfemales
Twitter: @codingblackfems

**Comment by yanco9a** [comment]
Maybe the invitation "timed-out" idk but it showing as pending 
![Screen Shot 2019-04-29 at 20 45 34](https://user-images.githubusercontent.com/32717839/56922349-e41e4e80-6abf-11e9-9d58-09500109fc2b.png)

**Comment by charlenehunter** [comment]
Hopefully it’s approved now?

Charlene

codingblackfemales.com
@codingblackfemales
Twitter: @codingblackfems
