### ISSUE TITLE
Create Events Database

### ISSUE THREAD

**Issue by charlenehunter** [CodingBlackFemales/cbf-community-website#44]
Create a database table that can store event data. At a minimum, the following information about an event must be stored:

- Event Date
- Event Location Latitude/Longitude
- Event Description

**Comment by yanco9a** [comment]
Firestore seems to be a good fit for this.

![Screen Shot 2019-05-23 at 15 14 45](https://user-images.githubusercontent.com/32717839/58260343-2dd02100-7d6e-11e9-98eb-2fdf488cabde.png)

source: https://cloud.google.com/firestore/quotas#free-quota

**Comment by yanco9a** [comment]
![Screen Shot 2019-06-03 at 08 15 33](https://user-images.githubusercontent.com/32717839/58783003-d3d62380-85d7-11e9-8c99-6e9fd96cb032.png)
